#! /bin/sh

set -e
(

dpkg-divert --package se3-logonpy --add --rename --divert /etc/samba/smb_CIFSFS.conf.divert  /etc/samba/smb_CIFSFS.conf
dpkg-divert --package se3-logonpy --add --rename --divert /etc/samba/smb_Samba.conf.divert  /etc/samba/smb_Samba.conf
 


) >/dev/null



exit 0
